# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: Kacerr's blog
author:
  name: Kacerr
  email: kacerr.cz@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Tech blog: place to share my ideas about (mostly) Kubernetes

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache      